# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-07-22 13:44
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190721_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True, max_length=500),
        ),
    ]
