# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-07-22 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190722_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verify_email',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
    ]
